apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "eaaaa64d-a4d0-4c5a-be68-46de7c89d550"
      - op: replace
        path: /spec/parameters/tenantId
        value: "2f695754-b89d-4b9b-b341-984f80794ebc"
      - op: replace
        path: /spec/parameters/keyvaultName
        value: "kv-venus-staging"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://venusbackupsstaging.blob.core.windows.net/customer1"
