apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "8a77e20f-f65e-4589-b730-b60d6dad3b13"
      - op: replace
        path: /spec/parameters/tenantId
        value: "2f695754-b89d-4b9b-b341-984f80794ebc"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://jupiterbackupsstaging.blob.core.windows.net/customer1"
