apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: customer1-tls
  namespace: customer1
spec:
  secretName: customer1-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - customer1.mercury.airmanbabu.net
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: customer1-n8n
  namespace: customer1
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`customer1.mercury.airmanbabu.net`)
      kind: Rule
      services:
        - name: customer1-n8n
          port: 3008
  tls:
    secretName: customer1-tls
