apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: barman-cloud-selfsigned-issuer
  namespace: cnpg-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barman-cloud-ca
  namespace: cnpg-system
spec:
  isCA: true
  commonName: barman-cloud-ca
  secretName: barman-cloud-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: barman-cloud-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: barman-cloud-ca-issuer
  namespace: cnpg-system
spec:
  ca:
    secretName: barman-cloud-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barman-cloud-server-tls
  namespace: cnpg-system
spec:
  secretName: barman-cloud-server-tls
  duration: 8760h
  renewBefore: 720h
  commonName: barman-cloud-server
  dnsNames:
    - barman-cloud-server
    - localhost
  usages:
    - server auth
    - key encipherment
    - digital signature
  issuerRef:
    name: barman-cloud-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barman-cloud-client-tls
  namespace: cnpg-system
spec:
  secretName: barman-cloud-client-tls
  duration: 8760h
  renewBefore: 720h
  commonName: barman-cloud-client
  usages:
    - client auth
    - key encipherment
    - digital signature
  issuerRef:
    name: barman-cloud-ca-issuer
    kind: Issuer
    group: cert-manager.io
